/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DmcaRequestService } from "../dmcaRequest.service";
import { DmcaRequestCreateInput } from "./DmcaRequestCreateInput";
import { DmcaRequest } from "./DmcaRequest";
import { DmcaRequestFindManyArgs } from "./DmcaRequestFindManyArgs";
import { DmcaRequestWhereUniqueInput } from "./DmcaRequestWhereUniqueInput";
import { DmcaRequestUpdateInput } from "./DmcaRequestUpdateInput";
import { LogFindManyArgs } from "../../log/base/LogFindManyArgs";
import { Log } from "../../log/base/Log";
import { LogWhereUniqueInput } from "../../log/base/LogWhereUniqueInput";

export class DmcaRequestControllerBase {
  constructor(protected readonly service: DmcaRequestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DmcaRequest })
  async createDmcaRequest(
    @common.Body() data: DmcaRequestCreateInput
  ): Promise<DmcaRequest> {
    return await this.service.createDmcaRequest({
      data: {
        ...data,

        content: data.content
          ? {
              connect: data.content,
            }
          : undefined,
      },
      select: {
        content: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        platformContact: true,
        requestDate: true,
        requestStatus: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DmcaRequest] })
  @ApiNestedQuery(DmcaRequestFindManyArgs)
  async dmcaRequests(@common.Req() request: Request): Promise<DmcaRequest[]> {
    const args = plainToClass(DmcaRequestFindManyArgs, request.query);
    return this.service.dmcaRequests({
      ...args,
      select: {
        content: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        platformContact: true,
        requestDate: true,
        requestStatus: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DmcaRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dmcaRequest(
    @common.Param() params: DmcaRequestWhereUniqueInput
  ): Promise<DmcaRequest | null> {
    const result = await this.service.dmcaRequest({
      where: params,
      select: {
        content: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        platformContact: true,
        requestDate: true,
        requestStatus: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DmcaRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDmcaRequest(
    @common.Param() params: DmcaRequestWhereUniqueInput,
    @common.Body() data: DmcaRequestUpdateInput
  ): Promise<DmcaRequest | null> {
    try {
      return await this.service.updateDmcaRequest({
        where: params,
        data: {
          ...data,

          content: data.content
            ? {
                connect: data.content,
              }
            : undefined,
        },
        select: {
          content: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          platformContact: true,
          requestDate: true,
          requestStatus: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DmcaRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDmcaRequest(
    @common.Param() params: DmcaRequestWhereUniqueInput
  ): Promise<DmcaRequest | null> {
    try {
      return await this.service.deleteDmcaRequest({
        where: params,
        select: {
          content: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          platformContact: true,
          requestDate: true,
          requestStatus: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/logs")
  @ApiNestedQuery(LogFindManyArgs)
  async findLogs(
    @common.Req() request: Request,
    @common.Param() params: DmcaRequestWhereUniqueInput
  ): Promise<Log[]> {
    const query = plainToClass(LogFindManyArgs, request.query);
    const results = await this.service.findLogs(params.id, {
      ...query,
      select: {
        content: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        dmcaRequest: {
          select: {
            id: true,
          },
        },

        id: true,
        logDate: true,
        logType: true,
        message: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/logs")
  async connectLogs(
    @common.Param() params: DmcaRequestWhereUniqueInput,
    @common.Body() body: LogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      logs: {
        connect: body,
      },
    };
    await this.service.updateDmcaRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/logs")
  async updateLogs(
    @common.Param() params: DmcaRequestWhereUniqueInput,
    @common.Body() body: LogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      logs: {
        set: body,
      },
    };
    await this.service.updateDmcaRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/logs")
  async disconnectLogs(
    @common.Param() params: DmcaRequestWhereUniqueInput,
    @common.Body() body: LogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      logs: {
        disconnect: body,
      },
    };
    await this.service.updateDmcaRequest({
      where: params,
      data,
      select: { id: true },
    });
  }
}
