/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Content } from "./Content";
import { ContentCountArgs } from "./ContentCountArgs";
import { ContentFindManyArgs } from "./ContentFindManyArgs";
import { ContentFindUniqueArgs } from "./ContentFindUniqueArgs";
import { CreateContentArgs } from "./CreateContentArgs";
import { UpdateContentArgs } from "./UpdateContentArgs";
import { DeleteContentArgs } from "./DeleteContentArgs";
import { DmcaRequestFindManyArgs } from "../../dmcaRequest/base/DmcaRequestFindManyArgs";
import { DmcaRequest } from "../../dmcaRequest/base/DmcaRequest";
import { LogFindManyArgs } from "../../log/base/LogFindManyArgs";
import { Log } from "../../log/base/Log";
import { Platform } from "../../platform/base/Platform";
import { ContentService } from "../content.service";
@graphql.Resolver(() => Content)
export class ContentResolverBase {
  constructor(protected readonly service: ContentService) {}

  async _contentsMeta(
    @graphql.Args() args: ContentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Content])
  async contents(
    @graphql.Args() args: ContentFindManyArgs
  ): Promise<Content[]> {
    return this.service.contents(args);
  }

  @graphql.Query(() => Content, { nullable: true })
  async content(
    @graphql.Args() args: ContentFindUniqueArgs
  ): Promise<Content | null> {
    const result = await this.service.content(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Content)
  async createContent(
    @graphql.Args() args: CreateContentArgs
  ): Promise<Content> {
    return await this.service.createContent({
      ...args,
      data: {
        ...args.data,

        platform: args.data.platform
          ? {
              connect: args.data.platform,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Content)
  async updateContent(
    @graphql.Args() args: UpdateContentArgs
  ): Promise<Content | null> {
    try {
      return await this.service.updateContent({
        ...args,
        data: {
          ...args.data,

          platform: args.data.platform
            ? {
                connect: args.data.platform,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Content)
  async deleteContent(
    @graphql.Args() args: DeleteContentArgs
  ): Promise<Content | null> {
    try {
      return await this.service.deleteContent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DmcaRequest], { name: "dmcaRequests" })
  async findDmcaRequests(
    @graphql.Parent() parent: Content,
    @graphql.Args() args: DmcaRequestFindManyArgs
  ): Promise<DmcaRequest[]> {
    const results = await this.service.findDmcaRequests(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Log], { name: "logs" })
  async findLogs(
    @graphql.Parent() parent: Content,
    @graphql.Args() args: LogFindManyArgs
  ): Promise<Log[]> {
    const results = await this.service.findLogs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Platform, {
    nullable: true,
    name: "platform",
  })
  async getPlatform(
    @graphql.Parent() parent: Content
  ): Promise<Platform | null> {
    const result = await this.service.getPlatform(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
